[package]
name = "br2-utils"
version = "0.1.1"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.3"
thiserror = "1.0.40"

tempdir = "0.3.7"
walkdir = "2.3.3"
clap = { version = "4.2.1", features = ["derive"] }
anyhow = "1.0.70"

[[bin]]
name = "br2-clerk"
